ClothesShop/Controllers/AuthenticationController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;

namespace ClothesShop.Controllers
{
    public class AuthenticationController : Controller
    {
        public IActionResult SignIn()
        {
            if (HttpContext.Session.GetInt32("adminId") == null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("Welcome", "Admin", null);
            }
        }
    }
}

ClothesShop/Controllers/UserController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using ClothesShop.Data;
using Microsoft.AspNetCore.Http;

namespace ClothesShop.Controllers
{
    public class UserController : Controller
    {
        private readonly ClothesShopContext _context;

        public UserController(ClothesShopContext context)
        {
            _context = context;
        }

        [HttpPost]
        public IActionResult Login(string email, string password)
        {
            if (email == null || password == null)
            {
                TempData["LoginFailed"] = true;
                return Redirect("/Authentication/SignIn");
            }

            var admin = _context.Admins.SingleOrDefault(u => u.Email == email && u.Password == password);

            if (admin == null)
            {
                TempData["LoginFailed"] = true;
                return Redirect("/Authentication/SignIn");
            }

            HttpContext.Session.SetInt32("adminId", admin.Id);
            HttpContext.Session.SetString("UserName", admin.UserName);

            return RedirectToAction("Welcome", "Admin", null);
        }

        public IActionResult Logout()
        {
            if (HttpContext.Session.GetInt32("adminId") == null)
            {
                return View("Views/Users/NotFound.cshtml");
            }

            HttpContext.Session.Remove("adminId");
            return RedirectToAction("Index", "Home", null);
        }
    }
}

ClothesShop/Views/Authentication/FailedLogin.cshtml
<h2 style="text-align:center">Login Failed</h2>
<div class="container-fluid">
    <div class="card">
        Sorry, we cant let you in. please check your credentials and try again later
        <br />
        <button type="button" class="btn btn-default" style="margin: 20px 0"> @Html.ActionLink("Try again", "SignIn", "Authentication")</button>
    </div>
</div>

ClothesShop/Views/Authentication/SignIn.cshtml
@{ if (TempData.ContainsKey("LoginFailed") && (bool)TempData["LoginFailed"] == true)
    {
        {
            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                <strong>Oops!</strong> The last login failed, please check your cardentials 
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        }
    }
}

<div class="container view-container">
    <div class="card card-signin my-5">
        <div class="card-body">
            <h5 class="card-title text-center">Sign In</h5>
            <form class="form-signin" asp-controller="User" asp-action="Login" method="POST">
                <div class="form-label-group">
                    <input type="email" name="email" id="inputEmail" class="form-control" placeholder="Email address" required autofocus>
                    <label for="inputEmail">Email address</label>
                </div>

                <div class="form-label-group">
                    <input type="password" autocomplete="off" name="password" id="inputPassword" class="form-control" placeholder="Password" required>
                    <label for="inputPassword">Password</label>
                </div>
                <button class="btn btn-lg btn-signin btn-block text-uppercase" type="submit">
                    SIGN IN
                </button>
                <hr class="my-4">
            </form>
        </div>
    </div>
</div>