ClothesShop/Models/Customer.cs
using System.ComponentModel.DataAnnotations;

namespace ClothesShop.Models
{
    public class Customer
    {
        [Key]
        public int Id { get; set; }

        public string FirstName { get; set; }

        public string LastName { get; set; }

        public string Gender { get; set; }

        public int Age { get; set; }

        public string Email { get; set; }
    }
}

ClothesShop/Models/Order.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;


namespace ClothesShop.Models
{
    public class Order
    {
        [Key]
        public int Id { get; set; }

        public Customer Customer { get; set; }

        public OrderStatus Status { get; set; }

        public string Address { get; set; }

        public string Zip { get; set; }

        public string CreditCardName { get; set; }

        public string CreditCardNumber { get; set; }

        public string CreditCardExpiration { get; set; }

        public string CreditCardCVV{ get; set; }

        public DateTime OrderDate { get; set; }

        public List<OrderItem> OrderItems { get; set; }

    }
}

ClothesShop/Models/Product.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;


namespace ClothesShop.Models
{
    public class Product : IComparable<Product>
    {
        [Key]
        public int Id { get; set; }
        public Category Category { get; set; }
        public string Name { get; set; }
        public int Price { get; set; }
        public Gender Gender { get; set; }
        public string ImageSrc { get; set; }
        public bool IsDeleted { get; set; }
        public List<Tag> Tags { get; set; }

        public int CompareTo(Product other)
        {
            return this.Id.CompareTo(other.Id);
        }
    }
}

ClothesShop/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ClothesShop.Models;
using ClothesShop.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Http;
using System.IO;
using Microsoft.AspNetCore.Hosting;

namespace ClothesShop.Controllers
{
    public class AdminController : Controller
    {
        private readonly ClothesShopContext _context;

        public AdminController(ClothesShopContext context) 
        {
            _context = context;
        }

        public class CustomerViewModel
        {
            public int Id { get; set; }
            public string FirstName { get; set; }
            public string LastName { get; set; }
            public string Gender { get; set; }
            public string Email { get; set; }
            public int OrdersNumber { get; set; }
        }

        public IActionResult Welcome()
        {
            if (HttpContext.Session.GetInt32("adminId") == null)
            {
                return View("Views/Users/NotFound.cshtml");
            }
            ViewBag.Name = HttpContext.Session.GetString("UserName");
            return View();
        }

        #region Products

        public IActionResult Products()
        {
            if (HttpContext.Session.GetInt32("adminId") == null)
            {
                return View("Views/Users/NotFound.cshtml");
            }

            List<Product> products = _context.Products.Include(p => p.Tags).ToList();
            List<Category> categories = _context.Categories.Where(cat => !cat.IsDeleted).ToList();
            List<Tag> tags = _context.Tags.Where(tag => !tag.IsDeleted).ToList();

            ViewBag.Products = products;
            ViewBag.Categories = categories;
            ViewBag.Tags = tags;
            return View();
        }

        public IActionResult RemoveProduct(int id)
        {
            if (HttpContext.Session.GetInt32("adminId") == null)
            {
                return View("Views/Users/NotFound.cshtml");
            }

            _context.Products.Single(p => p.Id == id).IsDeleted = true;

            try
            {
                _context.SaveChanges();
            }
            catch (Exception)
            {
                TempData["ProductRemovalFailed"] = true;
            }

            return Redirect("/Admin/Products");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddProduct(string name, int category, int price, IFormFile img, Gender gender, List<int> tags)
        {
            if (HttpContext.Session.GetInt32("adminId") == null)
            {
                return View("Views/Users/NotFound.cshtml");
            }

            string pathToSave = "";

            using (MemoryStream ms = new MemoryStream())
            {
                img.CopyTo(ms);
                var imageToSave = Convert.ToBase64String(ms.ToArray());
                pathToSave = "data:image/png;base64," + imageToSave;
            }

            Product newProduct = new Product()
            {
                Name = name,
                Category = _context.Categories.Single(c => c.Id == category),
                Price = price,
                ImageSrc = pathToSave,
                Gender = gender,
                Tags = _context.Tags.Where(t => tags.Contains(t.Id)).ToList()
            };

            _context.Add(newProduct);
            await _context.SaveChangesAsync();
            return Redirect("/Admin/Products");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditProduct(int id,
                                                      string name,
                                                      int category,
                                                      int price,
                                                      IFormFile img,
                                                      Gender gender,
                                                      List<int> tags)
        {
            if (HttpContext.Session.GetInt32("adminId") == null)
            {
                return View("Views/Users/NotFound.cshtml");
            }

            Product productToEdit = _context.Products.Include(p => p.Tags).Single(p => p.Id == id);
            productToEdit.Name = name;
            productToEdit.Category = _context.Categories.Single(c => c.Id == category);
            productToEdit.Price = price;
            productToEdit.Gender = gender;

            productToEdit.Tags.Clear();
            if (tags?.Any() == true)
            {
                foreach (Tag tag in _context.Tags.Where(t => tags.Contains(t.Id)))
                {
                    productToEdit.Tags.Add(tag);
                }
            }

            if (img != null)
            {
                using (MemoryStream ms = new MemoryStream())
                {
                    img.CopyTo(ms);
                    var imageToSave = Convert.ToBase64String(ms.ToArray(), 0, ms.ToArray().Length);
                    productToEdit.ImageSrc = "data:image/png;base64," + imageToSave;
                }
            }

            _context.Update(productToEdit);
            await _context.SaveChangesAsync();
            return Redirect("/Admin/Products");
        }

        #endregion

        #region Customers
        public IActionResult Customers()
        {
            if (HttpContext.Session.GetInt32("adminId") == null)
            {
                return View("Views/Users/NotFound.cshtml");
            }

            List<Customer> customers = _context.Customers.ToList();
            List<Order> orders = _context.Orders.ToList();
            List<CustomerViewModel> customerView = orders.GroupBy(g => g.Customer.Email)
                .Select(g =>
                {
                    var customer = customers.Single(c => c.Email == g.Key);
                    return new CustomerViewModel
                    {
                        Id = customer.Id,
                        FirstName = customer.FirstName,
                        LastName = customer.LastName,
                        Gender = customer.Gender,
                        Email = customer.Email,
                        OrdersNumber = g.Count()
                    };
                }).ToList();

            ViewBag.CustomersView = customerView;
            return View();
        }

        [HttpPost]
        public IActionResult Customers(string customerName)
        {
            if (HttpContext.Session.GetInt32("adminId") == null)
            {
                return View("Views/Users/NotFound.cshtml");
            }
            List<Customer> customers = _context.Customers.ToList();
            List<Order> orders = _context.Orders.ToList();
            List<CustomerViewModel> customerView = orders.GroupBy(g => g.Customer.Email)
                .Select(g =>
                {
                    var customer = customers.Single(c => c.Email == g.Key);
                    return new CustomerViewModel
                    {
                        Id = customer.Id,
                        FirstName = customer.FirstName,
                        LastName = customer.LastName,
                        Gender = customer.Gender,
                        Email = customer.Email,
                        OrdersNumber = g.Count()
                    };
                }).ToList();

            List<CustomerViewModel> wantedCustomerViews = new List<CustomerViewModel>();

            if (customerName != null)
            {
                wantedCustomerViews = customerView.Where((customer) => $"{customer.FirstName} {customer.LastName}" == customerName).ToList();
            }
            else
            {
                wantedCustomerViews = customerView;
            }
            
            ViewBag.CustomersView = wantedCustomerViews;

            return View();
        }

        public IActionResult RemoveCustomer(int id)
        {
            if (HttpContext.Session.GetInt32("adminId") == null)
            {
                return View("Views/Users/NotFound.cshtml");
            }

            if (_context.Orders.Include("Customer").First(o => o.Customer.Id == id) == null)
            {
                _context.Remove(_context.Customers.Single(b => b.Id == id));
                _context.SaveChanges();
            }
            else
            {
                TempData["CustomerRemovalFailed"] = true;
            }
            return Redirect("/Admin/Customers");
        }

        public IActionResult EditCustomer(int id, string firstName, string lastName)
        {
            if (HttpContext.Session.GetInt32("adminId") == null)
            {
                return View("Views/Users/NotFound.cshtml");
            }
            Customer customerToEdit = _context.Customers.Single(b => b.Id == id);

            customerToEdit.FirstName = firstName;
            customerToEdit.LastName = lastName;

            _context.Update(customerToEdit);
            _context.SaveChanges();
            return Redirect("/Admin/Customers");
        }

        #endregion

        #region Tags

        public IActionResult Tags()
        {
            if (HttpContext.Session.GetInt32("adminId") == null)
            {
                return View("Views/Users/NotFound.cshtml");
            }
            List<Tag> tags = _context.Tags.Where(cat => !cat.IsDeleted).ToList();
            ViewBag.Tags = tags;
            return View();
        }

        [HttpPost]
        public IActionResult Tags(string tagName)
        {
            if (HttpContext.Session.GetInt32("adminId") == null)
            {
                return View("Views/Users/NotFound.cshtml");
            }
            List<Tag> tags;

            if (tagName != null)
            {
                tags = _context.Tags.Where((tag) => tag.Name == tagName).ToList();
            }
            else
            {

ClothesShop/Controllers/FacebookController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ClothesShop.Models;
using ClothesShop.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Http;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using Facebook;

namespace ClothesShop.Controllers
{
    public class FacebookController : Controller
    {
        private readonly ClothesShopContext _context;
        private readonly IWebHostEnvironment webHostEnvironment;
        private readonly string pageToken;
        private readonly FacebookClient client;

        public FacebookController(ClothesShopContext context, IWebHostEnvironment iwebHostEnvironment) 
        {
            _context = context;
            webHostEnvironment = iwebHostEnvironment;
            pageToken = "EAAFAcZBZAUmBEBAMDgVtfBmYwE355MpZA8ySKRy3bYA4QBTQofCZAY4vRedYhuXmWUg6ivlxJpEP9dFt2nMTCQdfQErk1MsB3c9k6UwiqBYOpc4oZCmHeVVI8RdMYFZCJX5FkVUwDWuFZCrspeavYOdkwTk6pBbUmDiMXIBVOk99KFHTkdvywXh";
            client = new FacebookClient(pageToken);
        } 

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> postOnFacebook(string message, string link=null)
        {
            if (HttpContext.Session.GetInt32("adminId") == null)
            {
                return View("Views/Users/NotFound.cshtml");
            }

            var args = new Dictionary<string, object>();
            string postMessage = message;

            if (link != null)
            {
                postMessage = postMessage + "\n >>>>>>>>>>> " + link;
            }
            args["message"] = postMessage;

            await client.PostTaskAsync("/109078328141449/feed", args);

            return Redirect("/Admin/Welcome");
        }
    }
}

ClothesShop/Controllers/StatisticsController.cs
using ClothesShop.Data;
using ClothesShop.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Linq;

namespace ClothesShop.Controllers
{
    public class StatisticsController : Controller
    {
        private readonly ClothesShopContext _context;

        public StatisticsController(ClothesShopContext context)
        {
            _context = context;
        }

        [HttpGet]
        public ActionResult<List<GraphData>> ProductOrdersCount()
        {
            var productOrdersCountList = _context.OrderItems.Include(orderItem => orderItem.Product).ToList()
                                                            .GroupBy(i => i.Product)
                                                            .Select(o => new GraphData() { Name = o.Key.Name, Value = o.Sum(x => x.Quantity) })
                                                            .OrderBy(data => data.Value).ToList();
            return Ok(JsonConvert.SerializeObject(productOrdersCountList));
        }

       [HttpGet]
        public ActionResult<List<GraphData>> CategoriesOrdersCount()
        {
            var categoryOrdersCountList = _context.OrderItems
                .Join(_context.Products,
                order => order.Product.Id,
                product => product.Id,
                (order, product) => new
                {
                    product = product,
                    order = order
                }).Join(_context.Categories,
                order => order.product.Category.Id,
                category => category.Id,
                (order, category) => new
                {
                    order = order.order,
                    product = order.product,
                    category = category
                }).ToList()
                .GroupBy(x => x.category)
                .Select(o => new GraphData
                {
                    Name = o.Key.Name,
                    Value = o.Sum(order => order.order.Quantity)
                })
                .ToList();

            return Ok(JsonConvert.SerializeObject(categoryOrdersCountList));
        }

        [HttpGet]
        public ActionResult<List<GraphData>> ProfitPerMonth()
        {
            var profitPerMonthList = _context.OrderItems
                .Join(_context.Products,
                order => order.Product.Id,
                product => product.Id,
                (orderItem, product) => new
                {
                    product = product,
                    orderItem = orderItem
                }).Join(_context.Orders,
                orderDetails => orderDetails.orderItem.OrderId,
                order => order.Id,
                (orderDetails, order) => new
                {
                    orderItem = orderDetails.orderItem,
                    product = orderDetails.product,
                    order = order
                }).ToList()
                .OrderBy(x => x.order.OrderDate)
                .GroupBy(x => x.order.OrderDate.ToString("MM-yyyy"))
                .Select(o => new GraphData
                {
                    Name = o.Key.ToString(),
                    Value = o.Sum(order => order.orderItem.Quantity * order.product.Price)
                })
                .ToList();

            return Ok(JsonConvert.SerializeObject(profitPerMonthList));
        }

        [HttpGet]
        public ActionResult<List<GraphData>> OrderStatusCount()
        {
            var ordersStatusCount = _context.Orders
                .Join(_context.OrderStatuses,
                order => order.Status.Id,
                status => status.Id,
                (order, status) => new {
                    order = order,
                    status = status
                }).ToList()
                .GroupBy(x => x.status)
                .Select(o => new GraphData
                {
                    Name = o.Key.Name,
                    Value = o.Count()
                })
                .ToList();

            return Ok(JsonConvert.SerializeObject(ordersStatusCount));
        }
    }
}

ClothesShop/Views/Admin/Admins.cshtml
@{
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
    List<Admin> admins = ViewBag.Admins;
    int selfAdminId = ViewBag.SelfAdminId;
}

<h2>Admins</h2>
<div id="search" class="horizontal">
    <form id="searchForm" class="form-row align-items-center" asp-action="Admins" asp-controller="Admin" method="POST">
        <div class="col">
		        <label>By name:</label>
		        <input id="adminName" name="adminName" type="search" placeholder="type name to search.." class="form-control search-control ds-input" /> <br/>
            </div>
        <input type="submit" id="search-button" class="btn form-control search-control btn-primary btn-sm" value="Search">
    </form>
</div>

@{ foreach (Admin admin in admins)
    {
        <form class="edit-form d-flex">
            <div class="row w-100">
                <div class="col">
                    <input type="text" name="UserName" value="@admin.UserName" class="form-control ds-input" />
                </div>
                <div class="col">
                    <input type="email" name="Email" value="@admin.Email" pattern="^[a-zA-Z0-9._+-]+@("@")[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}$" class="form-control ds-input" />
                </div>
                <div class="col">
                    <input type="password" name="Password" value="@admin.Password" class="form-control ds-input" />
                </div>

                <div class="col">
                    <button type="submit" asp-controller="Admin" asp-action="EditAdmin" asp-route-id="@admin.Id" class="icon-button">
                        <i class="pnl-icon fa fa-save fa-lg"></i>
                    </button>
                    @{
                        if (!(admin.Id == selfAdminId))
                        {
                            <button type="submit" asp-route-id="@admin.Id" asp-controller="Admin" asp-action="RemoveAdmin" class="icon-button">
                                <i class="pnl-icon fa fa-trash fa-lg"></i>
                            </button>
                        }
                    }
                </div>
            </div>
        </form>
    }
}

<form id="add-category-form" class="horizontal" asp-action="AddAdmin" asp-controller="Admin" method="POST">
    <div class="row w-100">
        <div class="col">
            <input type="text" name="UserName" placeholder="UserName" required class="form-control ds-input" />
        </div>
        <div class="col">
            <input type="text" name="Email" placeholder="Email" required pattern="^[a-zA-Z0-9._+-]+@("@")[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}$" class="form-control ds-input" />
        </div>
        <div class="col">
            <input type="text" name="Password" placeholder="Password" required class="form-control ds-input" />
        </div>
        <input type="submit" id="search-button" class="btn btn-primary btn-sm" value="Add">
    </div>
</form>

ClothesShop/Views/Admin/Branches.cshtml
@{
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
    List<Branch> branches = ViewBag.Branches;
}

<h2>Branches</h2>
<div id="search" class="horizontal">
    <form id="searchForm" class="form-row align-items-center" asp-action="Branches" asp-controller="Admin" method="POST">
        <div class="col">
            <label>By name:</label>
            <input id="branchName" name="branchName" type="search" placeholder="type name to search.." class="form-control search-control ds-input" /> <br />
        </div>
        <input type="submit" id="search-button" class="btn form-control search-control btn-primary btn-sm" value="Search">
    </form>
</div>

@{ foreach (Branch branch in branches)
    {
        <form class="edit-form d-flex">
            <div class="row w-100">
                <div class="col">
                    <input type="text" name="name" value="@branch.BranchName" class="form-control ds-input" />
                </div>
                <div class="col">
                    <input type="text" name="address" value="@branch.AddressInfo" class="form-control ds-input" />
                </div>
                <div class="col">
                    <input type="number" name="x" value="@branch.LocationX" step="0.00001" pattern="[0-9]{2}\.[0-9]{5,}" class="form-control ds-input" />
                </div>
                <div class="col">
                    <input type="number" name="y" value="@branch.LocationY" step="0.00001" pattern="[0-9]{2}\.[0-9]{5,}" class="form-control ds-input" />
                </div>

                <div class="col">
                    <button type="submit" asp-controller="Admin" asp-action="EditBranch" asp-route-id="@branch.ID" class="icon-button">
                        <i class="pnl-icon fa fa-save fa-lg"></i>
                    </button>
                    <button type="submit" asp-route-id="@branch.ID" asp-controller="Admin" asp-action="RemoveBranch" class="icon-button">
                        <i class="pnl-icon fa fa-trash fa-lg"></i>
                    </button>
                </div>
            </div>
        </form>
    }
}

<form id="add-category-form" class="horizontal" asp-action="AddBranch" asp-controller="Admin" method="POST">
    <div class="row w-100">
        <div class="col">
            <input type="text" name="name" placeholder="Name" required class="form-control ds-input" />
        </div>
        <div class="col">
            <input type="text" name="address" placeholder="Address" required class="form-control ds-input" />
        </div>
        <div class="col">
            <input type="text" name="x" placeholder="X" step="0.00001"  pattern="[0-9]{2}\.[0-9]{5,}"  required class="form-control ds-input" />
        </div>
        <div class="col">
            <input type="text" name="y" placeholder="Y" step="0.00001"  pattern="[0-9]{2}\.[0-9]{5,}"  required class="form-control ds-input" />
        </div>
        <input type="submit" id="search-button" class="btn btn-primary btn-sm" value="Add">
    </div>
</form>

ClothesShop/Views/Admin/Categories.cshtml
@{
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
    List<Category> categories = ViewBag.Categories;
}

<h2>Categories</h2>
<div id="search" class="horizontal">
    <form id="searchForm" class="form-row align-items-center" asp-action="Categories" asp-controller="Admin" method="POST">
        <div class="col">
            <label>By name:</label>
            <input id="categoryName" name="categoryName" type="search" placeholder="type name to search.." class="form-control search-control ds-input" /> <br />
        </div>
        <input type="submit" id="search-button" class="btn form-control search-control btn-primary btn-sm" value="Search">
    </form>
</div>

@{ if (TempData.ContainsKey("CategoryRemovalFailed") && (bool)TempData["CategoryRemovalFailed"] == true)
    {
        {
            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                <strong>Oh no!</strong> You can't delete this category, because it's related to some products :(
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        }
    }
}

@{ foreach (Category category in categories)
    {
        <form class="edit-form d-flex">
            <input id="@category.Id" value="@category.Name" name="name" type="search" class="form-control ds-input" />
            <button class="icon-button" type="submit" asp-controller="Admin" asp-action="EditCategory" asp-route-id="@category.Id">
                <i class="pnl-icon fa fa-save fa-lg"></i>
            </button>
            <!-- Button trigger modal -->
            <button class="icon-button" type="submit" asp-route-id="@category.Id" asp-controller="Admin" asp-action="RemoveCategory">
                <i class="pnl-icon fa fa-trash fa-lg"></i>
            </button>
            <br />
        </form>
    }
}
<form id="add-category-form" class="horizontal" asp-action="AddCategory" asp-controller="Admin" method="POST">
    <input required id="add-category" name="name" type="search" class="form-control ds-input" />
    <input type="submit" id="search-button" class="btn btn-primary btn-sm" value="Add">
</form>

ClothesShop/Views/Admin/Customers.cshtml
@{
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
    var customersView = ViewBag.CustomersView;
}

@{ if (TempData.ContainsKey("CustomerRemovalFailed") && (bool)TempData["CustomerRemovalFailed"] == true)
    {
        {
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <strong>Oh no!</strong> You can't delete this customer, because it's related to some orders :(
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
        }
    }
}

<h2>Customers</h2>
<div id="search" class="horizontal">
    <form id="searchForm" class="form-row align-items-center" asp-action="Customers" asp-controller="Admin" method="POST">
        <div class="col">
            <label>By name:</label>
            <input id="customerName" name="customerName" type="search" placeholder="type name to search.." class="form-control search-control ds-input" /> <br />
        </div>
        <input type="submit" id="search-button" class="btn form-control search-control btn-primary btn-sm" value="Search">
    </form>
</div>

<table class="table">
    <thead class="thead-dark">
        <tr>
            <th scope="col">Name</th>
            <th scope="col">Mail</th>
            <th scope="col">Number Of Orders</th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        @{ foreach (var customer in customersView)
            {
                string editId = "edit-customer" + customer.Id;
                string editIdTarget = "#edit-customer" + customer.Id;
                <tr>
                    <td>@customer.FirstName @customer.LastName</td>
                    <td>@customer.Email</td>
                    <td>@customer.OrdersNumber</td>
                    <td>
                        <a data-toggle="modal" data-target="@editIdTarget">
                            <i class="pnl-icon fa fa-pencil fa-lg"></i>
                        </a>
                        <!-- Button trigger modal -->
                        <a asp-route-id="@customer.Id" asp-controller="Admin" asp-action="RemoveCustomer">
                            <i class="pnl-icon fa fa-trash fa-lg"></i>
                        </a>
                    </td>
                </tr>

                <!--Edit Product Modal -->
                <div class="modal fade" id="@editId" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="exampleModalLabel">Edit Customer</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <form class="" asp-action="EditCustomer" asp-controller="Admin" asp-route-id="@customer.Id" method="POST" enctype="multipart/form-data">
                                <div class="modal-body">
                                    <div class="form-group">
                                        <label for="editFirstName">First Name:</label>
                                        <input id="editFirstName" name="firstName" type="search" class="form-control ds-input" value="@customer.FirstName" />
                                    </div>
                                    <div class="form-group">
                                        <label for="editLastName">Last Name:</label>
                                        <input id="editLastName" name="lastName" type="search" class="form-control ds-input" value="@customer.LastName" />
                                    </div>
                                </div>
                                <div class="modal-footer">
                                    <input type="submit" id="search-button" class="btn btn-primary btn-sm" value="Edit">
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            }
        }

    </tbody>
</table>

ClothesShop/Views/Admin/FacebookPost.cshtml
@{
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
    string Name = ViewBag.Name;
}
<div class="container view-container">
    <div>
        <h2>Post on Facebook</h2>
        <h5>Share posts on your buisiness page</h5>
        <form class="form-facebook-post" asp-controller="Facebook" asp-action="postOnFacebook" method="POST">
            <div class="form-label-group">
                <input type="text" name="message" id="message" class="form-control" placeholder="your post content here" required>
                <label for="message">Post content</label>
            </div>

            <div class="form-label-group">
                <input type="url" name="link" id="link" class="form-control" placeholder="attach a link here">
                <label for="link">Link</label>
            </div>
            <button class="btn btn-lg btn-signin btn-block text-uppercase" type="submit">
                POST
            </button>
            <hr class="my-4">
        </form>
    </div>
</div>